TITLE: 'repr_table4_h36m_mpii3d_model'
DEBUG: false
DEBUG_FREQ: 5
LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'SAFM'
OUTPUT_DIR: 'experiments'
NUM_WORKERS: 16
SEED_VALUE: -1                
DATASET:
  SEQLEN: 9
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 300.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  D_MOTION_LOSS_W: 0.5
TRAIN:
  BATCH_SIZE: 32
  NUM_ITERS_PER_EPOCH: 500
  PRETRAINED: 'data/base_data/mpsnet_model_best.pth.tar'      # Change the field to the checkpoint you would like to evaluate
  PRETRAINED_REGRESSOR: 'data/base_data/spin_model_checkpoint.pth.tar'
  RESUME: ''
  START_EPOCH: 0
  END_EPOCH: 45
  LR_PATIENCE: 5
  DATA_2D_RATIO: 0.6
  OVERLAP: false
  DATASETS_2D:
    - 'Insta'
    - 'PoseTrack'
  DATASETS_3D:
    - 'ThreeDPW'
    - 'MPII3D'
    - 'Human36M'
  DATASET_EVAL: 'ThreeDPW'
  GEN_LR: 0.00005
  GEN_WD: 0.0
  MOT_DISCR:
    OPTIM: 'Adam'
    LR: 0.0001
    WD: 0.0001
    MOMENTUM: 0.9
    HIDDEN_SIZE: 1024
    NUM_LAYERS: 2
    FEATURE_POOL: 'attention'
    ATT:
      LAYERS: 3
      SIZE: 1024
      DROPOUT: 0.2
MODEL:
  TEMPORAL_TYPE: 'gru'
  TGRU:
    NUM_LAYERS: 2
    HIDDEN_SIZE: 1024
  PyMAF:
    MAF_ON: True
    BACKBONE: 'res50'
    MLP_DIM: [ 256, 128, 64, 5 ]
    N_ITER: 3
    AUX_SUPV_ON: True
RES_MODEL:
  DECONV_WITH_BIAS: False
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_DECONV_KERNELS:
  - 4
  - 4
  - 4